name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run test
      - name: Report coverage
        run: |
          curl -Lo ./cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          chmod +x ./cc-test-reporter
          ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json coverage/lcov.info
          ./cc-test-reporter upload-coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: maxmilton/action-setup-playwright@v1
        with:
          browsers: chromium
          headless: false
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn install --cwd=test/e2e --frozen-lockfile
      - run: xvfb-run --auto-servernum -- yarn run --cwd=test/e2e test-e2e
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn install --cwd=test/e2e --frozen-lockfile
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: yarn run lint
